# Generated by Django 2.0 on 2017-12-09 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePatternPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('object_type', models.IntegerField(choices=[(1, 'User'), (2, 'Team')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequestTransactionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('owner', models.CharField(max_length=250)),
                ('sender', models.CharField(max_length=250)),
                ('repository', models.CharField(max_length=250)),
                ('changed_files', models.TextField()),
                ('permission_violation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryFilePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pattern', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('authorized', models.ManyToManyField(to='github_messages.FilePatternPermissions')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('request_meta', models.TextField()),
                ('status', models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='pullrequesttransactionresult',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='github_messages.WebhookTransaction'),
        ),
    ]
